# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Tests

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        python-version: [3.8]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup Conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test
          environment-file: environment.yml
          python-version: 3.8
          auto-activate-base: false
      - name: Run tests
        shell: bash -l {0}
        run: |
          conda install pytest
          cd src
          pytest
      - name: Run scripts
        shell: bash -l {0}
        run: |
          cd src
          python analyse_images.py -d test_data
